server:
  port: 8000

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:http://localhost:8888}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: formation-service
          uri: lb://formation-service
          predicates:
            - Path=/formations/**
        - id: formation-service-swagger
          uri: lb://formation-service
          predicates:
            - Path=/v3/api-docs/**
        - id: emploidutemps-service
          uri: lb://emploidutemps-service
          predicates:
            - Path=/seances/**
        - id: joboffre-service
          uri: lb://joboffre-service
          predicates:
            - Path=/joboffers/**
        - id: certification-service
          uri: lb://certification-service
          predicates:
            - Path=/certifications/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: INFO